#!/bin/dash
if [ -d "./.pig" ]
then
    echo "pigs-init: error: .pig already exists"
else
    mkdir ".pig"
    mkdir "./.pig/index"
    mkdir "./.pig/repo"
    touch "./.pig/.log"
    echo "Initialized empty pigs repository in .pig"
fi